# Generated by Django 2.2.4 on 2019-08-25 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_faculte', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('nom_faculte',),
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_institution', models.CharField(max_length=50)),
                ('adresse', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('fondateur', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
            options={
                'ordering': ('nom_institution',),
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_option', models.CharField(max_length=50)),
                ('moyenne', models.CharField(max_length=50)),
                ('nbre_de_cours', models.IntegerField()),
                ('no_faculter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.Faculter')),
            ],
            options={
                'ordering': ('nom_option',),
            },
        ),
        migrations.AddField(
            model_name='faculter',
            name='no_institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.Institution'),
        ),
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_expert', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('sexe', models.CharField(max_length=50)),
                ('universiter', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('option', models.CharField(max_length=50)),
                ('no_faculter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.Faculter')),
            ],
            options={
                'ordering': ('nom_expert',),
            },
        ),
    ]
